# THIS IS EXPERIMENTAL
# the config file schema may change at any time

style:
  tag:
    color: green
    width_percentage: 15 # column width relative to the terminal window
    min_width: 15 # minimum column width as number of characters
  comment:
    color: blue
    width_percentage: 50
    min_width: 50
  snippet:
    color: white
    width_percentage: 35
    min_width: 35


finder:
  command: fzf
  # overrides: --tac # equivalent to the --fzf-overrides option
  # overrides_var: --tac # equivalent to the --fzf-overrides-var option

#cheats:
  #paths:
#     - /path/to/some/dir # on unix-like os
#     - F:\\path\\to\\dir # on Windows

# search:
#   tags: git,!checkout # equivalent to the --tag-rules option

# client:
#   tealdeer: true # enables tealdeer support for navi --tldr

shell:
  # Shell used for shell out. Possible values: bash, zsh, dash, ...
  # For Windows, use `cmd.exe` instead.
  command: bash

  # finder_command: bash # similar, but for fzf's internals

